creating entities
Stanley-Maraba/budgetApp pull request #1
Opened 2023-03-24 08:21 UTC by Stanley-Maraba

2023-03-24 08:34 UTC, colsen-neslo requested changes

2023-03-24 08:34 UTC, colsen-neslo commented on pom.xml
> +			<dependency>
Fix formatting

2023-03-24 08:34 UTC, colsen-neslo commented on src/main/java/com/budgetapp/entities/caregory.java
> +public class caregory {
Follow Java case standards

2023-03-24 08:34 UTC, colsen-neslo commented on src/main/java/com/budgetapp/entities/caregory.java
> +@Table(name = "user")
Table name does not match class name.

2023-03-24 08:34 UTC, colsen-neslo commented on src/main/java/com/budgetapp/entities/caregory.java
> +import jakarta.persistence.*;
Rather user javax persistence api.

2023-03-24 08:34 UTC, colsen-neslo commented on src/main/java/com/budgetapp/entities/caregory.java
> +import jakarta.persistence.*;
Avoid using wildcard imports and only import the exact api's as needed.

2023-03-24 08:34 UTC, colsen-neslo commented on src/main/java/com/budgetapp/entities/expence.java
> +public class expence {
```suggestion
@Table(name = "expense")
public class Expense {
```

2023-03-24 08:34 UTC, colsen-neslo commented on src/main/java/com/budgetapp/entities/expence.java
> +    private Integer id;
You can create an abstract entity that your entities extend from that will contain any common attributes for your domain models.

2023-03-24 08:34 UTC, colsen-neslo commented on src/main/java/com/budgetapp/entities/user.java
> +public class user {
```suggestion
@Table(name = "user")
public class User {
```

2023-03-24 08:34 UTC, colsen-neslo commented on src/main/java/org/example/Main.java
> +public class Main {
This is not required, you are building a spring boot app.

2023-03-24 08:34 UTC, colsen-neslo commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
Make use of a property that can create and update.

2023-03-24 14:09 UTC, colsen-neslo requested changes

2023-03-24 14:09 UTC, colsen-neslo commented on pom.xml
> +				<artifactId>postgresql</artifactId>
Fix formatting

2023-03-24 14:09 UTC, colsen-neslo commented on src/main/java/com/budgetapp/entities/User.java
> +    public String getName() {
Make sure your getters and setters are named correctly to the field.
```suggestion
    public String getUsername() {
```

2023-03-24 14:09 UTC, colsen-neslo commented on src/main/java/com/budgetapp/entities/User.java
> +    public void setName(String name) {
```suggestion
    public void setUsername(String name) {
```

2023-03-24 14:09 UTC, colsen-neslo commented on src/main/java/org/example/Main.java
> +public class Main {
This hasn't been removed.

2023-03-24 14:10 UTC, JOlsen-Neslo requested changes
Nice first attempt! Left some comments regarding the style of code we expect. Let me know if anything is unclear so we can chat about it.

Also, please make sure each PR that you create is based on a ticket on the JIRA board. The branch name should be in this format: `feature/SBA-{ticket-number}`

Then make sure each commit is prefixed with the issue code and number: `SBA-123: create entities`

2023-03-24 14:10 UTC, JOlsen-Neslo commented on pom.xml
> +				<groupId>org.postgresql</groupId>
Fix your formatting in this file

2023-03-24 14:10 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/BudgetappApplication.java
> +	public static void main(String[] args) {
All parameters for functions should be marked as final

2023-03-24 14:10 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/BudgetappApplication.java
> +	}
The indent size is different across your classes, make sure your config is set and keep each file formatted the same please

2023-03-24 14:10 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/Category.java
> +public class Category extends BaseEntity{
Please format this file

2023-03-24 14:10 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/Category.java
> +    public void setName(String name) {
```suggestion
    public void setName(final String name) {
```

2023-03-24 14:10 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/Category.java
> +    public String getName() {
Up to you, but I generally like to use the Lombok library to dynamically create accessor and mutators to keep the class lean

2023-03-24 14:10 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/Expense.java
> +@Table(name = "expense")
lowercase or Pascal case is fine, but please make sure all entities follow the same standard

`Category` vs `expense`

Should be:

`categories` vs `expenses`

or 

`Categories` vs `Expenses`

2023-03-24 14:10 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/Category.java
> +@Table(name = "Category")
Table names should be in plural form

```suggestion
@Table(name = "Categories")
```

2023-03-24 14:10 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/Expense.java
> +
Make sure there aren't any trailing blank lines across your app where its not needed. A tool like Checkstyle could help enforce this at compile time.

Also, please format this class

2023-03-24 14:10 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/Expense.java
> +    public void setName(String name) {
```suggestion
    public void setName(final String name) {
```

2023-03-24 14:10 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/Expense.java
> +    public void setValue(Integer value) {
```suggestion
    public void setValue(final Integer value) {
```

2023-03-24 14:10 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/Expense.java
> +    private Integer value;
When dealing with monetary values, its generally good practice to use `BigDecimal` so you can cater for cent values

2023-03-24 14:10 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/User.java
> +
Same comment here regarding blank lines and formatting

2023-03-24 14:10 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/User.java
> +    public void setName(String name) {
Mark all parameters as final

2023-03-27 09:16 UTC, colsen-neslo requested changes

2023-03-27 09:16 UTC, colsen-neslo commented on src/main/java/com/budgetapp/entities/Category.java
> +public class Category extends BaseEntity{
This is still outstanding.

2023-03-27 09:16 UTC, colsen-neslo commented on src/main/java/com/budgetapp/entities/User.java
> +    public String getName() {
This still needs to be done

2023-03-27 09:16 UTC, colsen-neslo commented on src/main/java/com/budgetapp/entities/User.java
>  public class User extends BaseEntity{
Please use your IDE to format all your classes (`cmd + option + L`)

2023-03-27 11:19 UTC, colsen-neslo approved these changes

2023-03-27 11:34 UTC, JOlsen-Neslo requested changes

2023-03-27 11:34 UTC, JOlsen-Neslo commented on pom.xml
> +			<dependency>
This formatting is still off

2023-03-27 11:34 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/Expense.java
> +@Table(name = "expenses")
```suggestion
@Table(name = "Expenses")
```

2023-03-27 13:25 UTC, JOlsen-Neslo approved these changes

2023-03-27 13:25 UTC, merged