Creating controller and service packages
Stanley-Maraba/budgetApp pull request #2
Opened 2023-03-24 13:56 UTC by Stanley-Maraba

2023-03-24 14:17 UTC, JOlsen-Neslo requested changes

2023-03-24 14:17 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/controller/UserController.java
> +private final UserService userService;
Please format this class

2023-03-24 14:17 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/controller/UserController.java
> +package com.budgetapp.controller;
since your entities package is pluralised, please make sure this package is too

2023-03-24 14:17 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/controller/UserController.java
> +    public UserController(UserService userService) {
```suggestion
    public UserController(final UserService userService) {
```

2023-03-24 14:17 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/controller/UserController.java
> +    @GetMapping("/user")
Following RESTful API design, you want to make sure your resource paths are plural

```suggestion
    @GetMapping("/users")
```

2023-03-24 14:17 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/controller/UserController.java
> +    @PostMapping("/saveUser")
Following RESTful API design, API paths shouldn't be named after actions. Below is an example of how your API paths should be defined:

`GET /users` - list all users
`POST /users` - creates a new user
`GET /users/{id}` - finds a specific user
`PUT /users/{id}` - updates a specific user
`DELETE /users/{id}` - deletes a specific user

2023-03-24 14:17 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/BaseEntity.java
> +import jakarta.persistence.Column;
jakarta? Shouldn't this be from JPA?

2023-03-24 14:17 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/BaseEntity.java
> +    public void setId(Integer id) {
```suggestion
    public void setId(final Integer id) {
```

2023-03-24 14:17 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/services/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
This repository seems redundant, just use the CrudRepository you have defined

2023-03-24 14:17 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/services/UserService.java
> +
remove this extra blank line

2023-03-24 14:17 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/services/UserService.java
> +    public UserService(UserRepository userRepository, UserCrudRepository userCrudRepository) {
```suggestion
    public UserService(final UserRepository userRepository, final UserCrudRepository userCrudRepository) {
```

2023-03-24 14:17 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/services/UserService.java
> +    public User FindByUsername(String username)
please make sure you follow Java naming conventions for methods

```suggestion
    public User findByUsername(final String username)
```

2023-03-24 14:17 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/services/UserService.java
> +    public void saveUser(User user)
```suggestion
    public void saveUser(final User user)
```

2023-03-24 14:17 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/services/UserService.java
> +
remove this extra blank line

2023-03-24 14:21 UTC, colsen-neslo requested changes

2023-03-24 14:21 UTC, colsen-neslo commented on src/main/java/com/budgetapp/services/UserCrudRepository.java
> +public interface UserCrudRepository extends CrudRepository<User, Long> {
This is redundant, the JPA repo extend the crud repo.

2023-03-24 14:21 UTC, colsen-neslo commented on src/main/java/com/budgetapp/services/UserRepository.java
> +package com.budgetapp.services;
```suggestion
package com.budgetapp.repositories;
```

2023-03-24 14:21 UTC, colsen-neslo commented on src/main/java/com/budgetapp/services/UserService.java
> +    public User FindByUsername(String username)
Follow camelCase standards for method names.

2023-03-24 14:21 UTC, colsen-neslo commented on src/main/java/com/budgetapp/services/UserService.java
> +    {
Rather don't drop the first brace.

2023-03-28 12:26 UTC, colsen-neslo requested changes

2023-03-28 12:26 UTC, colsen-neslo commented on src/main/java/com/budgetapp/Repositories/ExpensesRepository.java
> +package com.budgetapp.Repositories;
```suggestion
package com.budgetapp.repositories;
```

2023-03-28 12:26 UTC, colsen-neslo commented on src/main/java/com/budgetapp/controllers/CategoryController.java
>      }
```suggestion
    @PostMapping(
         consumes = MediaType.APPLICATION_JSON_VALUE,
         produces = MediaType.APPLICATION_JSON_VALUE
    )
    public ResponseEntity<Category> addCategory(@RequestBody final Category category) {
        final var createdCategory = categoryService.addCategory(category);
        return ResponseEntity
                .status(HttpStatus.CREATED)
                .body(createdCategory );
    }
```
Please make sure all your controller endpoints follow the standard of returning a `ResponseEntity` object with the correct statuses and bodies based on what they are doing. Check the [HttpStatus Codes](https://www.semrush.com/blog/http-status-codes/?kw=&cmp=Africa_SRCH_DSA_Blog_EN&label=dsa_pagefeed&Network=g&Device=c&utm_content=622528804255&kwid=dsa-1754723155433&cmpid=18364843126&agpid=141057021083&BU=Core&extid=60114153143&adpos=&gclid=CjwKCAjwoIqhBhAGEiwArXT7K5dcw8D9JDfkxvB-rWrEhk038xRrqZb4koXr7eeEE14ZuOZcxYCNvhoCi-oQAvD_BwE) link.

2023-03-28 12:26 UTC, colsen-neslo commented on src/main/java/com/budgetapp/controllers/CategoryController.java
>      }
Please make sure you apply the above suggestion to all endpoints.

2023-03-28 12:33 UTC, JOlsen-Neslo requested changes

2023-03-28 12:33 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/controllers/CategoryController.java
> +    private CategoryService categoryService;
mark this as `private final` and inject it into the constructor

2023-03-28 12:33 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/BudgetappApplication/BudgetappApplication.java
> +    public static void main(String[] args) {
mark all method parameters as `final`

2023-03-28 12:33 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/controllers/CategoryController.java
> +    public void addCategory(@RequestBody Category category) {
mark all method parameters as final

2023-03-28 12:33 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/controllers/CategoryController.java
> +    public void deleteCategory(@PathVariable Long id) {
Make sure you are using the ResponseEntity object as the response on all endpoints

2023-03-28 12:33 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/controllers/UserController.java
> +    private UserService userService;
Mark this as final

2023-03-28 12:33 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/controllers/UserController.java
> +    public void createUser(@RequestBody User user) {
mark all parameters as `final`

2023-03-28 12:33 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/controllers/UserController.java
> +        User user = userService.findUserById(id);
Mark all local variables as final

2023-03-28 12:33 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/User.java
> +public class User extends BaseEntity{
Please format this class

2023-03-28 12:33 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/services/UserService.java
> +
extra blank line is still here

2023-03-28 12:33 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/services/UserService.java
> +    private UserRepository userRepository;
mark as final and inject this into the constructor

2023-03-28 12:33 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/controllers/CategoryController.java
> +public class CategoryController {
Does this compile? Where is the category service?

2023-03-28 12:33 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/services/UserService.java
> +        Optional<User> optionalUser = userRepository.findById(id);
You should rather throw an EntityNotFoundException when this occurs. You will then need to add exception handlers to return a 404 error response

2023-03-28 12:40 UTC, Stanley-Maraba commented on src/main/java/com/budgetapp/controllers/CategoryController.java
> +public class CategoryController {
line 18

2023-03-28 14:49 UTC, colsen-neslo commented on src/main/java/com/budgetapp/controllers/CategoryController.java
> +public class CategoryController {
@Stanley-Maraba there is no file committed for the CategoryService

2023-03-30 07:25 UTC, colsen-neslo requested changes

2023-03-30 07:25 UTC, colsen-neslo commented on src/main/java/com/budgetapp/controllers/UserController.java
>      @GetMapping()
Please add the produces mediatype here!!

2023-03-30 07:25 UTC, colsen-neslo commented on src/main/java/com/budgetapp/controllers/UserController.java
> +        try {
Rather use an Exception handler bean to intercept the exceptions and handle the correct response.

2023-03-30 07:25 UTC, colsen-neslo commented on src/main/java/com/budgetapp/services/UserService.java
> +        User user = userRepository.findById(id).orElseThrow(EntityNotFoundException::new);
Instead of just throwing a new EntityNotFoundException rather add a custom message to the exception stating why the user could not be found.

2023-03-30 07:50 UTC, JOlsen-Neslo requested changes

2023-03-30 07:50 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/services/UserService.java
> +    public UserService(UserRepository userRepository) {
mark this parameter as final

2023-03-30 07:50 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/services/UserService.java
> +        User user = userRepository.findById(id).orElseThrow(EntityNotFoundException::new);
also remember to mark the local variable as final

2023-03-30 09:44 UTC, JOlsen-Neslo requested changes

2023-03-30 09:44 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/controllers/UserController.java
> +        User user = userService.findUserById(id);
this still needs to be done

2023-03-30 09:44 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/exceptions/CustomExceptionHandler.java
> +    public ResponseEntity<Object> handlingEntityNotFound(Exception ex)
Mark this parameter as final

2023-03-30 09:44 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/exceptions/CustomExceptionHandler.java
> +                .body(ex.getMessage());
I would suggest sending back the error message in some sort of custom error object. Something like this:

```json
{
   "message": "blah blah blah"
}
```

2023-03-30 09:44 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/services/CategoryService.java
> +    public CategoryService(CategoryRepository categoryRepository) {
mark as final

2023-03-30 09:44 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/services/ExpensesService.java
> +    public ExpensesService(ExpensesRepository expensesRepository) {
mark as final

2023-03-30 09:44 UTC, colsen-neslo requested changes

2023-03-30 09:44 UTC, colsen-neslo commented on src/main/java/com/budgetapp/controllers/ExpensesController.java
> +@RequestMapping(path = "/api/expenses", consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
Rather add the media types on a method level instead of on the class level.

2023-03-30 09:44 UTC, colsen-neslo commented on src/main/java/com/budgetapp/controllers/UserController.java
> +        User user = userService.findUserById(id);
This is still outstanding.

2023-03-30 09:44 UTC, colsen-neslo commented on src/main/java/com/budgetapp/exceptions/CustomExceptionHandler.java
> +    public ResponseEntity<Object> handlingEntityNotFound(Exception ex)
```suggestion
    public ResponseEntity<Object> handlingEntityNotFound(EntityNotFoundException ex)
```

2023-03-30 09:44 UTC, colsen-neslo commented on src/main/java/com/budgetapp/exceptions/CustomExceptionHandler.java
> +    {
Don't drop this brace..

2023-03-30 09:44 UTC, colsen-neslo commented on src/main/java/com/budgetapp/services/CategoryService.java
> +    public CategoryService(CategoryRepository categoryRepository) {
```suggestion
    public CategoryService(final CategoryRepository categoryRepository) {
```

2023-03-30 09:44 UTC, colsen-neslo commented on src/main/java/com/budgetapp/services/ExpensesService.java
> +    public ExpensesService(ExpensesRepository expensesRepository) {
```suggestion
    public ExpensesService(final ExpensesRepository expensesRepository) {
```

2023-03-30 09:44 UTC, colsen-neslo commented on src/main/java/com/budgetapp/services/ExpensesService.java
> +    public Expense addExpenses(final Expense expenses) {
```suggestion
    public Expense addExpenses(final Expense expense) {
```

2023-03-30 09:44 UTC, colsen-neslo commented on src/main/java/com/budgetapp/services/UserService.java
> +        User user = userRepository.findById(id).orElseThrow(() -> new EntityNotFoundException("user with id : " + id + " is not found"));
```suggestion
        final var user = userRepository.findById(id).orElseThrow(() -> new EntityNotFoundException(String.format("user with id : %s is not found", id)));
```

2023-03-30 10:35 UTC, colsen-neslo approved these changes

2023-03-30 10:35 UTC, colsen-neslo commented on src/main/java/com/budgetapp/services/UserService.java
> +        final User user = userRepository.findById(id).orElseThrow(() -> new EntityNotFoundException(String.format("user with id : %s is not     found", id)));
Just check your spacing here.
```suggestion
        final User user = userRepository.findById(id).orElseThrow(() -> new EntityNotFoundException(String.format("user with id : %s is not found", id)));
```

2023-03-30 11:32 UTC, JOlsen-Neslo approved these changes

2023-03-30 11:32 UTC, merged