TRAIN-152: creating entity relationships
Stanley-Maraba/budgetApp pull request #3
Opened 2023-04-05 09:06 UTC by Stanley-Maraba

2023-04-05 11:09 UTC, JOlsen-Neslo requested changes

2023-04-05 11:09 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/User.java
> +    private Integer Income;
```suggestion
    private Integer income;
```

2023-04-05 11:09 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/Expense.java
> +    @ManyToOne
It is good practice to define explicitly what the join column should be as well as proving a unique foreign key name

```suggestion
    @ManyToOne
    @JoinColumn(
            name = "user_id",
            foreignKey = @ForeignKey(name = "users_fk")
    )
```

2023-04-05 11:09 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/Expense.java
> +    @ManyToOne
```suggestion
    @ManyToOne
    @JoinColumn(
            name = "category_id",
            foreignKey = @ForeignKey(name = "categories_fk")
    )
```

2023-04-05 15:38 UTC, colsen-neslo commented on src/main/java/com/budgetapp/entities/User.java
> +    private Integer Income;
Do you not want to create a separate entity for Income? What if a user has multiple forms of income?

2023-04-11 06:52 UTC, colsen-neslo requested changes

2023-04-11 06:52 UTC, colsen-neslo commented on src/main/java/com/budgetapp/entities/Income.java
> +    public void setName(String name) {
Make sure the params are declared as final.

2023-04-11 06:52 UTC, colsen-neslo commented on src/main/java/com/budgetapp/services/IncomeService.java
> +    public Income addIncome(final Income income) {
I think you need a retrieve 1 and retrieve all service.

2023-04-11 08:12 UTC, colsen-neslo approved these changes

2023-04-11 08:28 UTC, JOlsen-Neslo requested changes

2023-04-11 08:28 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/User.java
> +    private List<Expense> expenses;
Shouldn't we add the same for incomes?

2023-04-12 07:56 UTC, JOlsen-Neslo requested changes

2023-04-12 07:56 UTC, JOlsen-Neslo commented on src/main/java/com/budgetapp/entities/User.java
> +    private List<Expense> expenses;
You still haven't added incomes here

2023-04-12 13:55 UTC, JOlsen-Neslo approved these changes

2023-04-12 13:55 UTC, merged